# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codestore',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardian.Guardian', unique=True, verbose_name='guardian'),
        ),
        migrations.AlterField(
            model_name='telegramidstore',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardian.Guardian', unique=True, verbose_name='guardian'),
        ),
        migrations.AlterField(
            model_name='telegramidstore',
            name='telegram_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Telegram id'),
        ),
    ]
