# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170827_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codestore',
            name='guardian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guardian.Guardian', verbose_name='guardian'),
        ),
        migrations.AlterField(
            model_name='telegramidstore',
            name='guardian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guardian.Guardian', verbose_name='guardian'),
        ),
    ]
