# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170827_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramidstore',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='codestore',
            name='guardian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='guardian.Guardian', verbose_name='guardian'),
        ),
        migrations.AlterField(
            model_name='telegramidstore',
            name='guardian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to='guardian.Guardian', verbose_name='guardian'),
        ),
        migrations.AlterField(
            model_name='telegramidstore',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram id'),
        ),
    ]
