# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardian', '0003_auto_20170827_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('age', models.SmallIntegerField(blank=True, null=True, verbose_name='age')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='guardian.Guardian')),
            ],
            options={
                'verbose_name': 'kid',
                'verbose_name_plural': 'kids',
            },
        ),
    ]
