# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='guardian.Guardian'),
        ),
    ]
