# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kid', '0002_auto_20170827_1750'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kid',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
