# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0005_auto_20170827_1856'),
        ('kid', '0003_auto_20170827_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('A', 'absence'), ('R', 'request')], max_length=1, verbose_name='Report type')),
                ('description', models.TextField(verbose_name='Description')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='kid.Kid')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='guardian.Guardian')),
            ],
        ),
    ]
