# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0002_auto_20170827_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardian',
            options={'verbose_name': 'guardian', 'verbose_name_plural': 'guardians'},
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='password',
        ),
    ]
