# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:09
from __future__ import unicode_literals

import alibot.guardian.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0003_auto_20170827_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='mobile_number',
            field=models.CharField(max_length=11, validators=[alibot.guardian.validators.MobileNumberValidator()], verbose_name='Mobile number'),
        ),
        migrations.AlterUniqueTogether(
            name='guardian',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
