# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0004_auto_20170827_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='last_login_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Last login code'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='last_login_code_request',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last login code request'),
        ),
    ]
